# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 22:55
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(app.models.GameTypeChoice('Training (Doppel)'), 'Training (Doppel)'), (app.models.GameTypeChoice('Training (Einzel)'), 'Training (Einzel)'), (app.models.GameTypeChoice('Turnier'), 'Turnier'), (app.models.GameTypeChoice('Event'), 'Event')], max_length=5)),
                ('number', models.PositiveSmallIntegerField()),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
