# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 23:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Reservierung', 'verbose_name_plural': 'Reservierungen'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1, help_text='Stundenanzahl', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Dauer'),
        ),
        migrations.AddField(
            model_name='event',
            name='externPlayer1',
            field=models.CharField(blank=True, help_text='Name des ersten externen Mitspielers', max_length=200, verbose_name='Externer1'),
        ),
        migrations.AddField(
            model_name='event',
            name='externPlayer2',
            field=models.CharField(blank=True, help_text='Name des zweiten externen Mitspielers', max_length=200, verbose_name='Externer2'),
        ),
        migrations.AddField(
            model_name='event',
            name='externPlayer3',
            field=models.CharField(blank=True, help_text='Name des dritten externen Mitspielers', max_length=200, verbose_name='Externer3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='Tag der Reservierung', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Beschreibung/Zusätzliche Infos', null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Beginn der Reservierung', verbose_name='Stratzeit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
