# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-10 15:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190226_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='Tag der Reservierung', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.PositiveSmallIntegerField(default=3, help_text='Nummer des Tennisplatzes', validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Platznummer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='Wähle dich und deine/n Mitspieler aus', related_name='otherplayers', to=settings.AUTH_USER_MODEL, verbose_name='Spieler'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Einzelspiel', 'Einzelspiel'), ('Doppelspiel', 'Doppelspiel'), ('Turnier', 'Turnier'), ('Event', 'Event'), ('Arbeitseinsatz', 'Arbeitseinsatz'), ('Medenrunde', 'Medenrunde')], help_text='Art des Trainings', max_length=200, verbose_name='Einzel/Doppel'),
        ),
    ]
