# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 19:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, default=3, help_text='Nummer des Tennisplatzes', validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Platznummer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Einzelspiel', 'Einzelspiel'), ('Doppelspiel', 'Doppelspiel'), ('Turnier', 'Turnier'), ('Event', 'Event'), ('Arbeitseinsatz', 'Arbeitseinsatz'), ('Medenrunde', 'Medenrunde'), ('Training', 'Training')], help_text='Art des Trainings', max_length=200, verbose_name='Einzel/Doppel'),
        ),
    ]
