# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190324_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Stundenanzahl', verbose_name='Dauer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Einzelspiel', 'Einzelspiel'), ('Doppelspiel', 'Doppelspiel'), ('Turnier', 'Turnier'), ('Event', 'Event'), ('Arbeitseinsatz', 'Arbeitseinsatz'), ('Medenrunde', 'Medenrunde'), ('Training', 'Training')], help_text='Art des Trainings', max_length=200, verbose_name='Event-Typ'),
        ),
    ]
