# Generated by Django 2.0.5 on 2019-04-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190327_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='Wähle deine/n Mitspieler aus', related_name='otherplayers', to=settings.AUTH_USER_MODEL, verbose_name='Spieler'),
        ),
    ]
